// Generated by rstantools.  Do not edit by hand.

#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_mica_corr_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 50> locations_array__ =
  {" (found before start of program)",
  " (in 'mica_corr', line 22, column 2 to column 28)",
  " (in 'mica_corr', line 23, column 2 to column 20)",
  " (in 'mica_corr', line 24, column 2 to column 27)",
  " (in 'mica_corr', line 27, column 2 to column 56)",
  " (in 'mica_corr', line 28, column 2 to column 23)",
  " (in 'mica_corr', line 52, column 2 to column 25)",
  " (in 'mica_corr', line 30, column 4 to column 26)",
  " (in 'mica_corr', line 31, column 4 to column 26)",
  " (in 'mica_corr', line 32, column 4 to column 55)",
  " (in 'mica_corr', line 33, column 4 to column 52)",
  " (in 'mica_corr', line 29, column 21 to line 34, column 3)",
  " (in 'mica_corr', line 29, column 2 to line 34, column 3)",
  " (in 'mica_corr', line 37, column 2 to column 33)",
  " (in 'mica_corr', line 38, column 2 to column 30)",
  " (in 'mica_corr', line 39, column 2 to column 28)",
  " (in 'mica_corr', line 41, column 4 to column 27)",
  " (in 'mica_corr', line 42, column 4 to column 27)",
  " (in 'mica_corr', line 43, column 4 to column 55)",
  " (in 'mica_corr', line 44, column 4 to column 30)",
  " (in 'mica_corr', line 45, column 4 to column 77)",
  " (in 'mica_corr', line 40, column 22 to line 46, column 3)",
  " (in 'mica_corr', line 40, column 2 to line 46, column 3)",
  " (in 'mica_corr', line 48, column 4 to column 63)",
  " (in 'mica_corr', line 47, column 21 to line 49, column 3)",
  " (in 'mica_corr', line 47, column 2 to line 49, column 3)",
  " (in 'mica_corr', line 9, column 2 to column 17)",
  " (in 'mica_corr', line 10, column 2 to column 21)",
  " (in 'mica_corr', line 11, column 8 to column 13)",
  " (in 'mica_corr', line 11, column 2 to column 48)",
  " (in 'mica_corr', line 12, column 9 to column 14)",
  " (in 'mica_corr', line 12, column 2 to column 22)",
  " (in 'mica_corr', line 13, column 18 to column 23)",
  " (in 'mica_corr', line 13, column 2 to column 41)",
  " (in 'mica_corr', line 14, column 2 to column 22)",
  " (in 'mica_corr', line 15, column 8 to column 14)",
  " (in 'mica_corr', line 15, column 2 to column 50)",
  " (in 'mica_corr', line 16, column 9 to column 15)",
  " (in 'mica_corr', line 16, column 2 to column 30)",
  " (in 'mica_corr', line 17, column 18 to column 24)",
  " (in 'mica_corr', line 17, column 2 to column 39)",
  " (in 'mica_corr', line 18, column 2 to column 27)",
  " (in 'mica_corr', line 19, column 2 to column 24)",
  " (in 'mica_corr', line 22, column 23 to column 24)",
  " (in 'mica_corr', line 24, column 9 to column 14)",
  " (in 'mica_corr', line 27, column 9 to column 10)",
  " (in 'mica_corr', line 27, column 12 to column 13)",
  " (in 'mica_corr', line 28, column 9 to column 14)",
  " (in 'mica_corr', line 52, column 9 to column 10)",
  " (in 'mica_corr', line 52, column 12 to column 13)"};
#include <stan_meta_header.hpp>
class model_mica_corr final : public model_base_crtp<model_mica_corr> {
private:
  int d;
  int n_obs;
  std::vector<std::vector<int>> obs_idx;
  Eigen::Matrix<double,-1,1> z_obs_data__;
  Eigen::Matrix<double,-1,1> within_prec_obs_data__;
  int n_miss;
  std::vector<std::vector<int>> miss_idx;
  Eigen::Matrix<double,-1,1> prior_mean_z_data__;
  Eigen::Matrix<double,-1,1> prior_prec_z_data__;
  double tau2_scale;
  double lkj_eta;
  Eigen::Map<Eigen::Matrix<double,-1,1>> z_obs{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> within_prec_obs{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> prior_mean_z{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> prior_prec_z{nullptr, 0};
public:
  ~model_mica_corr() {}
  model_mica_corr(stan::io::var_context& context__, unsigned int
                  random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_mica_corr_namespace::model_mica_corr";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 26;
      context__.validate_dims("data initialization", "d", "int",
        std::vector<size_t>{});
      d = std::numeric_limits<int>::min();
      current_statement__ = 26;
      d = context__.vals_i("d")[(1 - 1)];
      current_statement__ = 26;
      stan::math::check_greater_or_equal(function__, "d", d, 2);
      current_statement__ = 27;
      context__.validate_dims("data initialization", "n_obs", "int",
        std::vector<size_t>{});
      n_obs = std::numeric_limits<int>::min();
      current_statement__ = 27;
      n_obs = context__.vals_i("n_obs")[(1 - 1)];
      current_statement__ = 27;
      stan::math::check_greater_or_equal(function__, "n_obs", n_obs, 0);
      current_statement__ = 28;
      stan::math::validate_non_negative_index("obs_idx", "n_obs", n_obs);
      current_statement__ = 29;
      context__.validate_dims("data initialization", "obs_idx", "int",
        std::vector<size_t>{static_cast<size_t>(n_obs),
          static_cast<size_t>(2)});
      obs_idx = std::vector<std::vector<int>>(n_obs,
                  std::vector<int>(2, std::numeric_limits<int>::min()));
      {
        std::vector<int> obs_idx_flat__;
        current_statement__ = 29;
        obs_idx_flat__ = context__.vals_i("obs_idx");
        current_statement__ = 29;
        pos__ = 1;
        current_statement__ = 29;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 29;
          for (int sym2__ = 1; sym2__ <= n_obs; ++sym2__) {
            current_statement__ = 29;
            stan::model::assign(obs_idx, obs_idx_flat__[(pos__ - 1)],
              "assigning variable obs_idx", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 29;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 29;
      stan::math::check_greater_or_equal(function__, "obs_idx", obs_idx, 1);
      current_statement__ = 29;
      stan::math::check_less_or_equal(function__, "obs_idx", obs_idx, d);
      current_statement__ = 30;
      stan::math::validate_non_negative_index("z_obs", "n_obs", n_obs);
      current_statement__ = 31;
      context__.validate_dims("data initialization", "z_obs", "double",
        std::vector<size_t>{static_cast<size_t>(n_obs)});
      z_obs_data__ = Eigen::Matrix<double,-1,1>::Constant(n_obs,
                       std::numeric_limits<double>::quiet_NaN());
      new (&z_obs)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(z_obs_data__.data(), n_obs);
      {
        std::vector<local_scalar_t__> z_obs_flat__;
        current_statement__ = 31;
        z_obs_flat__ = context__.vals_r("z_obs");
        current_statement__ = 31;
        pos__ = 1;
        current_statement__ = 31;
        for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
          current_statement__ = 31;
          stan::model::assign(z_obs, z_obs_flat__[(pos__ - 1)],
            "assigning variable z_obs", stan::model::index_uni(sym1__));
          current_statement__ = 31;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 32;
      stan::math::validate_non_negative_index("within_prec_obs", "n_obs",
        n_obs);
      current_statement__ = 33;
      context__.validate_dims("data initialization", "within_prec_obs",
        "double", std::vector<size_t>{static_cast<size_t>(n_obs)});
      within_prec_obs_data__ = Eigen::Matrix<double,-1,1>::Constant(n_obs,
                                 std::numeric_limits<double>::quiet_NaN());
      new (&within_prec_obs)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(within_prec_obs_data__.data(),
        n_obs);
      {
        std::vector<local_scalar_t__> within_prec_obs_flat__;
        current_statement__ = 33;
        within_prec_obs_flat__ = context__.vals_r("within_prec_obs");
        current_statement__ = 33;
        pos__ = 1;
        current_statement__ = 33;
        for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
          current_statement__ = 33;
          stan::model::assign(within_prec_obs, within_prec_obs_flat__[(pos__
            - 1)], "assigning variable within_prec_obs",
            stan::model::index_uni(sym1__));
          current_statement__ = 33;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 33;
      stan::math::check_greater_or_equal(function__, "within_prec_obs",
        within_prec_obs, 0);
      current_statement__ = 34;
      context__.validate_dims("data initialization", "n_miss", "int",
        std::vector<size_t>{});
      n_miss = std::numeric_limits<int>::min();
      current_statement__ = 34;
      n_miss = context__.vals_i("n_miss")[(1 - 1)];
      current_statement__ = 34;
      stan::math::check_greater_or_equal(function__, "n_miss", n_miss, 0);
      current_statement__ = 35;
      stan::math::validate_non_negative_index("miss_idx", "n_miss", n_miss);
      current_statement__ = 36;
      context__.validate_dims("data initialization", "miss_idx", "int",
        std::vector<size_t>{static_cast<size_t>(n_miss),
          static_cast<size_t>(2)});
      miss_idx = std::vector<std::vector<int>>(n_miss,
                   std::vector<int>(2, std::numeric_limits<int>::min()));
      {
        std::vector<int> miss_idx_flat__;
        current_statement__ = 36;
        miss_idx_flat__ = context__.vals_i("miss_idx");
        current_statement__ = 36;
        pos__ = 1;
        current_statement__ = 36;
        for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
          current_statement__ = 36;
          for (int sym2__ = 1; sym2__ <= n_miss; ++sym2__) {
            current_statement__ = 36;
            stan::model::assign(miss_idx, miss_idx_flat__[(pos__ - 1)],
              "assigning variable miss_idx", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 36;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 36;
      stan::math::check_greater_or_equal(function__, "miss_idx", miss_idx, 1);
      current_statement__ = 36;
      stan::math::check_less_or_equal(function__, "miss_idx", miss_idx, d);
      current_statement__ = 37;
      stan::math::validate_non_negative_index("prior_mean_z", "n_miss",
        n_miss);
      current_statement__ = 38;
      context__.validate_dims("data initialization", "prior_mean_z",
        "double", std::vector<size_t>{static_cast<size_t>(n_miss)});
      prior_mean_z_data__ = Eigen::Matrix<double,-1,1>::Constant(n_miss,
                              std::numeric_limits<double>::quiet_NaN());
      new (&prior_mean_z)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(prior_mean_z_data__.data(),
        n_miss);
      {
        std::vector<local_scalar_t__> prior_mean_z_flat__;
        current_statement__ = 38;
        prior_mean_z_flat__ = context__.vals_r("prior_mean_z");
        current_statement__ = 38;
        pos__ = 1;
        current_statement__ = 38;
        for (int sym1__ = 1; sym1__ <= n_miss; ++sym1__) {
          current_statement__ = 38;
          stan::model::assign(prior_mean_z, prior_mean_z_flat__[(pos__ - 1)],
            "assigning variable prior_mean_z", stan::model::index_uni(sym1__));
          current_statement__ = 38;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 39;
      stan::math::validate_non_negative_index("prior_prec_z", "n_miss",
        n_miss);
      current_statement__ = 40;
      context__.validate_dims("data initialization", "prior_prec_z",
        "double", std::vector<size_t>{static_cast<size_t>(n_miss)});
      prior_prec_z_data__ = Eigen::Matrix<double,-1,1>::Constant(n_miss,
                              std::numeric_limits<double>::quiet_NaN());
      new (&prior_prec_z)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(prior_prec_z_data__.data(),
        n_miss);
      {
        std::vector<local_scalar_t__> prior_prec_z_flat__;
        current_statement__ = 40;
        prior_prec_z_flat__ = context__.vals_r("prior_prec_z");
        current_statement__ = 40;
        pos__ = 1;
        current_statement__ = 40;
        for (int sym1__ = 1; sym1__ <= n_miss; ++sym1__) {
          current_statement__ = 40;
          stan::model::assign(prior_prec_z, prior_prec_z_flat__[(pos__ - 1)],
            "assigning variable prior_prec_z", stan::model::index_uni(sym1__));
          current_statement__ = 40;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 40;
      stan::math::check_greater_or_equal(function__, "prior_prec_z",
        prior_prec_z, 0);
      current_statement__ = 41;
      context__.validate_dims("data initialization", "tau2_scale", "double",
        std::vector<size_t>{});
      tau2_scale = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 41;
      tau2_scale = context__.vals_r("tau2_scale")[(1 - 1)];
      current_statement__ = 41;
      stan::math::check_greater_or_equal(function__, "tau2_scale",
        tau2_scale, 0);
      current_statement__ = 42;
      context__.validate_dims("data initialization", "lkj_eta", "double",
        std::vector<size_t>{});
      lkj_eta = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 42;
      lkj_eta = context__.vals_r("lkj_eta")[(1 - 1)];
      current_statement__ = 42;
      stan::math::check_greater_or_equal(function__, "lkj_eta", lkj_eta, 0);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("L", "d", d);
      current_statement__ = 43;
      stan::math::validate_non_negative_index("L", "d", d);
      current_statement__ = 44;
      stan::math::validate_non_negative_index("true_z_raw", "n_obs", n_obs);
      current_statement__ = 45;
      stan::math::validate_non_negative_index("R", "d", d);
      current_statement__ = 46;
      stan::math::validate_non_negative_index("R", "d", d);
      current_statement__ = 47;
      stan::math::validate_non_negative_index("true_z", "n_obs", n_obs);
      current_statement__ = 48;
      stan::math::validate_non_negative_index("R_out", "d", d);
      current_statement__ = 49;
      stan::math::validate_non_negative_index("R_out", "d", d);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = ((d * (d - 1)) / 2) + 1 + n_obs;
  }
  inline std::string model_name() const final {
    return "model_mica_corr";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_mica_corr_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,-1> L =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(d, d, DUMMY_VAR__);
      current_statement__ = 1;
      L = in__.template read_constrain_cholesky_factor_corr<
            Eigen::Matrix<local_scalar_t__,-1,-1>, jacobian__>(lp__, d);
      local_scalar_t__ tau = DUMMY_VAR__;
      current_statement__ = 2;
      tau = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> true_z_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_obs, DUMMY_VAR__);
      current_statement__ = 3;
      true_z_raw = in__.template read<
                     Eigen::Matrix<local_scalar_t__,-1,1>>(n_obs);
      Eigen::Matrix<local_scalar_t__,-1,-1> R =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(d, d, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(R,
        stan::math::multiply_lower_tri_self_transpose(L),
        "assigning variable R");
      Eigen::Matrix<local_scalar_t__,-1,1> true_z =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_obs, DUMMY_VAR__);
      current_statement__ = 12;
      for (int o = 1; o <= n_obs; ++o) {
        int i = std::numeric_limits<int>::min();
        current_statement__ = 7;
        i = stan::model::rvalue(obs_idx, "obs_idx",
              stan::model::index_uni(o), stan::model::index_uni(1));
        int j = std::numeric_limits<int>::min();
        current_statement__ = 8;
        j = stan::model::rvalue(obs_idx, "obs_idx",
              stan::model::index_uni(o), stan::model::index_uni(2));
        local_scalar_t__ r_clip = DUMMY_VAR__;
        current_statement__ = 9;
        r_clip = stan::math::fmax(
                   stan::math::fmin(
                     stan::model::rvalue(R, "R", stan::model::index_uni(i),
                       stan::model::index_uni(j)), 0.9999), -0.9999);
        current_statement__ = 10;
        stan::model::assign(true_z, (stan::math::atanh(r_clip) + (tau *
          stan::model::rvalue(true_z_raw, "true_z_raw",
            stan::model::index_uni(o)))), "assigning variable true_z",
          stan::model::index_uni(o));
      }
      {
        current_statement__ = 13;
        lp_accum__.add(stan::math::lkj_corr_cholesky_lpdf<propto__>(L,
                         lkj_eta));
        current_statement__ = 14;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(tau, 0, tau2_scale));
        current_statement__ = 15;
        lp_accum__.add(stan::math::std_normal_lpdf<propto__>(true_z_raw));
        current_statement__ = 22;
        for (int m = 1; m <= n_miss; ++m) {
          int i = std::numeric_limits<int>::min();
          current_statement__ = 16;
          i = stan::model::rvalue(miss_idx, "miss_idx",
                stan::model::index_uni(m), stan::model::index_uni(1));
          int j = std::numeric_limits<int>::min();
          current_statement__ = 17;
          j = stan::model::rvalue(miss_idx, "miss_idx",
                stan::model::index_uni(m), stan::model::index_uni(2));
          local_scalar_t__ r_clip = DUMMY_VAR__;
          current_statement__ = 18;
          r_clip = stan::math::fmax(
                     stan::math::fmin(
                       stan::model::rvalue(R, "R", stan::model::index_uni(i),
                         stan::model::index_uni(j)), 0.9999), -0.9999);
          local_scalar_t__ z_ij = DUMMY_VAR__;
          current_statement__ = 19;
          z_ij = stan::math::atanh(r_clip);
          current_statement__ = 20;
          lp_accum__.add(stan::math::normal_lpdf<false>(z_ij,
                           stan::model::rvalue(prior_mean_z, "prior_mean_z",
                             stan::model::index_uni(m)),
                           stan::math::inv_sqrt(
                             stan::model::rvalue(prior_prec_z,
                               "prior_prec_z", stan::model::index_uni(m)))));
        }
        current_statement__ = 25;
        for (int o = 1; o <= n_obs; ++o) {
          current_statement__ = 23;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::model::rvalue(z_obs, "z_obs",
                             stan::model::index_uni(o)),
                           stan::model::rvalue(true_z, "true_z",
                             stan::model::index_uni(o)),
                           stan::math::inv_sqrt(
                             stan::model::rvalue(within_prec_obs,
                               "within_prec_obs", stan::model::index_uni(o)))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_mica_corr_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,-1> L =
        Eigen::Matrix<double,-1,-1>::Constant(d, d,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      L = in__.template read_constrain_cholesky_factor_corr<
            Eigen::Matrix<local_scalar_t__,-1,-1>, jacobian__>(lp__, d);
      double tau = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      tau = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<double,-1,1> true_z_raw =
        Eigen::Matrix<double,-1,1>::Constant(n_obs,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      true_z_raw = in__.template read<
                     Eigen::Matrix<local_scalar_t__,-1,1>>(n_obs);
      Eigen::Matrix<double,-1,-1> R =
        Eigen::Matrix<double,-1,-1>::Constant(d, d,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> true_z =
        Eigen::Matrix<double,-1,1>::Constant(n_obs,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(L);
      out__.write(tau);
      out__.write(true_z_raw);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 4;
      stan::model::assign(R,
        stan::math::multiply_lower_tri_self_transpose(L),
        "assigning variable R");
      current_statement__ = 12;
      for (int o = 1; o <= n_obs; ++o) {
        int i = std::numeric_limits<int>::min();
        current_statement__ = 7;
        i = stan::model::rvalue(obs_idx, "obs_idx",
              stan::model::index_uni(o), stan::model::index_uni(1));
        int j = std::numeric_limits<int>::min();
        current_statement__ = 8;
        j = stan::model::rvalue(obs_idx, "obs_idx",
              stan::model::index_uni(o), stan::model::index_uni(2));
        double r_clip = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 9;
        r_clip = stan::math::fmax(
                   stan::math::fmin(
                     stan::model::rvalue(R, "R", stan::model::index_uni(i),
                       stan::model::index_uni(j)), 0.9999), -0.9999);
        current_statement__ = 10;
        stan::model::assign(true_z, (stan::math::atanh(r_clip) + (tau *
          stan::model::rvalue(true_z_raw, "true_z_raw",
            stan::model::index_uni(o)))), "assigning variable true_z",
          stan::model::index_uni(o));
      }
      if (emit_transformed_parameters__) {
        out__.write(R);
        out__.write(true_z);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,-1> R_out =
        Eigen::Matrix<double,-1,-1>::Constant(d, d,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 6;
      stan::model::assign(R_out, R, "assigning variable R_out");
      out__.write(R_out);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,-1> L =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(d, d, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(L,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(d, d),
        "assigning variable L");
      out__.write_free_cholesky_factor_corr(L);
      local_scalar_t__ tau = DUMMY_VAR__;
      current_statement__ = 2;
      tau = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, tau);
      Eigen::Matrix<local_scalar_t__,-1,1> true_z_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_obs, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(true_z_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(n_obs),
        "assigning variable true_z_raw");
      out__.write(true_z_raw);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "L", "double",
        std::vector<size_t>{static_cast<size_t>(d), static_cast<size_t>(d)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "tau", "double",
        std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "true_z_raw",
        "double", std::vector<size_t>{static_cast<size_t>(n_obs)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,-1> L =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(d, d, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> L_flat__;
        current_statement__ = 1;
        L_flat__ = context__.vals_r("L");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
          current_statement__ = 1;
          for (int sym2__ = 1; sym2__ <= d; ++sym2__) {
            current_statement__ = 1;
            stan::model::assign(L, L_flat__[(pos__ - 1)],
              "assigning variable L", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 1;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_cholesky_factor_corr(L);
      local_scalar_t__ tau = DUMMY_VAR__;
      current_statement__ = 2;
      tau = context__.vals_r("tau")[(1 - 1)];
      out__.write_free_lb(0, tau);
      Eigen::Matrix<local_scalar_t__,-1,1> true_z_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(n_obs, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> true_z_raw_flat__;
        current_statement__ = 3;
        true_z_raw_flat__ = context__.vals_r("true_z_raw");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
          current_statement__ = 3;
          stan::model::assign(true_z_raw, true_z_raw_flat__[(pos__ - 1)],
            "assigning variable true_z_raw", stan::model::index_uni(sym1__));
          current_statement__ = 3;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(true_z_raw);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"L", "tau", "true_z_raw"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"R", "true_z"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"R_out"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(d),
                                                 static_cast<size_t>(d)},
                std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(n_obs)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(d),
               static_cast<size_t>(d)},
             std::vector<size_t>{static_cast<size_t>(n_obs)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(d),
               static_cast<size_t>(d)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= d; ++sym2__) {
        param_names__.emplace_back(std::string() + "L" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    param_names__.emplace_back(std::string() + "tau");
    for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
      param_names__.emplace_back(std::string() + "true_z_raw" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= d; ++sym2__) {
          param_names__.emplace_back(std::string() + "R" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        param_names__.emplace_back(std::string() + "true_z" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= d; ++sym2__) {
          param_names__.emplace_back(std::string() + "R_out" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= ((d * (d - 1)) / 2); ++sym1__) {
      param_names__.emplace_back(std::string() + "L" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "tau");
    for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
      param_names__.emplace_back(std::string() + "true_z_raw" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= d; ++sym2__) {
          param_names__.emplace_back(std::string() + "R" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        param_names__.emplace_back(std::string() + "true_z" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= d; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= d; ++sym2__) {
          param_names__.emplace_back(std::string() + "R_out" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"L\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(d) + ",\"cols\":" + std::to_string(d) + "},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"true_z_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_obs) + "},\"block\":\"parameters\"},{\"name\":\"R\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(d) + ",\"cols\":" + std::to_string(d) + "},\"block\":\"transformed_parameters\"},{\"name\":\"true_z\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_obs) + "},\"block\":\"transformed_parameters\"},{\"name\":\"R_out\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(d) + ",\"cols\":" + std::to_string(d) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"L\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(((d * (d - 1)) /2)) + "},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"true_z_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_obs) + "},\"block\":\"parameters\"},{\"name\":\"R\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(d) + ",\"cols\":" + std::to_string(d) + "},\"block\":\"transformed_parameters\"},{\"name\":\"true_z\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(n_obs) + "},\"block\":\"transformed_parameters\"},{\"name\":\"R_out\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(d) + ",\"cols\":" + std::to_string(d) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((d * d) + 1) + n_obs);
    const size_t num_transformed = emit_transformed_parameters * (((d * d) +
      n_obs));
    const size_t num_gen_quantities = emit_generated_quantities * ((d * d));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((d * d) + 1) + n_obs);
    const size_t num_transformed = emit_transformed_parameters * (((d * d) +
      n_obs));
    const size_t num_gen_quantities = emit_generated_quantities * ((d * d));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_mica_corr_namespace::model_mica_corr;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_mica_corr_namespace::profiles__;
}
#endif
#endif
